name: Build and Upload Binaries

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Stage 1: Build and upload C binary
    - name: Build C binary
      run: |
        cd c_binary
        ./configure
        make
        ./hello  # Replace with actual executable name if different

    - name: Upload C binary artifact
      uses: actions/upload-artifact@v4
      with:
        name: c-binary
        path: ./c_binary/hello  # Adjust this to your binary file path

    # Stage 2: Build and upload C++ binary
    - name: Build C++ binary
      run: |
        mkdir -p cpp_binary/build
        cd cpp_binary/build
        cmake ..
        make
        ./myapp  # Replace with actual executable name if different

    - name: Upload C++ binary artifact
      uses: actions/upload-artifact@v4
      with:
        name: cpp-binary
        path: ./cpp_binary/build/myapp  # Adjust the path to your C++ binary executable

    # Stage 3: Build and upload Rust binary
    - name: Build Rust binary
      run: |
        cd rust_binary/hello_world
        cargo build --release
        ./target/release/hello_world  # Replace with actual executable name if different

    - name: Upload Rust binary artifact
      uses: actions/upload-artifact@v4
      with:
        name: rust-binary
        path: rust_binary/hello_world/target/release/hello_world  # Adjust path if necessary

    # Stage 4: Build and Deploy Rust Documentation
    - name: Build Rust documentation
      run: |
        cd rust_binary/hello_world
        cargo doc --no-deps
    
    - name: Copy Rust docs to site folder
      run: |
        rm -rf docs/hello_world
        mkdir -p docs/hello_world
        cp -r rust_binary/hello_world/target/doc/* docs/hello_world/
    
    - name: Configure Git for commit
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
    
    - name: Commit and push documentation updates
      run: |
        git add docs/
        git diff --cached --quiet || (git commit -m "Update Rust documentation" && git push)
